# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

matrix:
  include:
#    - python: 2.7
#      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

install:
  - pip install -r requirements.txt
  - pip install tox coverage

script: tox

after_success: coverage report

notifications:
email: false